/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as IconPreviewRouteImport } from './routes/icon-preview'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const IconPreviewRoute = IconPreviewRouteImport.update({
  id: '/icon-preview',
  path: '/icon-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/icon-preview': typeof IconPreviewRoute
  '/politica': typeof PoliticaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/icon-preview': typeof IconPreviewRoute
  '/politica': typeof PoliticaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/icon-preview': typeof IconPreviewRoute
  '/politica': typeof PoliticaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/icon-preview' | '/politica'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/icon-preview' | '/politica'
  id: '__root__' | '/' | '/icon-preview' | '/politica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IconPreviewRoute: typeof IconPreviewRoute
  PoliticaRoute: typeof PoliticaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icon-preview': {
      id: '/icon-preview'
      path: '/icon-preview'
      fullPath: '/icon-preview'
      preLoaderRoute: typeof IconPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IconPreviewRoute: IconPreviewRoute,
  PoliticaRoute: PoliticaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
